DROP SEQUENCE MONUMENTO_SEQ IF EXISTS;
CREATE SEQUENCE MONUMENTO_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO MONUMENTO (ID, COD_PAIS, NOMBRE_PAIS, NOMBRE_CIUDAD, LATITUD, LONGITUD, NOMBRE_MONUMENTO, DESCRIPCION, FOTO_URL) VALUES (NEXTVAL('MONUMENTO_SEQ'),'FR','Francia','París', 20.2, 22.4, 'Torre Eiffel','Torre principal en una de las ciudades emblemáticas de Francia','https://www.empacher.com/fileadmin/EN/products/racing-boats/racing-four/Steuer_unter_Deck__steering_device_integrated_inside_canvas.JPG');
INSERT INTO MONUMENTO (ID, COD_PAIS, NOMBRE_PAIS, NOMBRE_CIUDAD, LATITUD, LONGITUD, NOMBRE_MONUMENTO, DESCRIPCION, FOTO_URL) VALUES (NEXTVAL('MONUMENTO_SEQ'),'ES','España','Sevilla', 21.2, 12.4, 'Giralda','Torre que forma parte de la catedral de Sevilla','https://www.empacher.com/fileadmin/EN/products/racing-boats/racing-four/Steuer_unter_Deck__steering_device_integrated_inside_canvas.JPG');
INSERT INTO MONUMENTO (ID, COD_PAIS, NOMBRE_PAIS, NOMBRE_CIUDAD, LATITUD, LONGITUD, NOMBRE_MONUMENTO, DESCRIPCION, FOTO_URL) VALUES (NEXTVAL('MONUMENTO_SEQ'),'ES','España','Sevilla', 20.2, 22.4, 'Plaza España','Plaza que se encuentra en el Parque de Maria Luisa','https://www.empacher.com/fileadmin/EN/products/racing-boats/racing-four/Steuer_unter_Deck__steering_device_integrated_inside_canvas.JPG');
INSERT INTO MONUMENTO (ID, COD_PAIS, NOMBRE_PAIS, NOMBRE_CIUDAD, LATITUD, LONGITUD, NOMBRE_MONUMENTO, DESCRIPCION, FOTO_URL) VALUES (NEXTVAL('MONUMENTO_SEQ'),'CH','Chile','Isla de Pascua', 20.2, 22.4, 'Moáis de la isla de Pascua','Cabezas de moais en un paradero','https://www.empacher.com/fileadmin/EN/products/racing-boats/racing-four/Steuer_unter_Deck__steering_device_integrated_inside_canvas.JPG');
INSERT INTO MONUMENTO (ID, COD_PAIS, NOMBRE_PAIS, NOMBRE_CIUDAD, LATITUD, LONGITUD, NOMBRE_MONUMENTO, DESCRIPCION, FOTO_URL) VALUES (NEXTVAL('MONUMENTO_SEQ'),'RU','Rusia','Moscu', 20.2, 22.4, 'Kremlin','Edificios civiles, palacios, las murallas de la antigua fortaleza y construcciones religiosas como la Catedral de San Basilio','https://www.empacher.com/fileadmin/EN/products/racing-boats/racing-four/Steuer_unter_Deck__steering_device_integrated_inside_canvas.JPG');
INSERT INTO MONUMENTO (ID, COD_PAIS, NOMBRE_PAIS, NOMBRE_CIUDAD, LATITUD, LONGITUD, NOMBRE_MONUMENTO, DESCRIPCION, FOTO_URL) VALUES (NEXTVAL('MONUMENTO_SEQ'),'EA','Emiratos Arabes Unidos','Dubai', 20.2, 22.4, 'Burj Khalifa','Con sus ¡828 metros! es el edificio más grande del planeta','https://www.empacher.com/fileadmin/EN/products/racing-boats/racing-four/Steuer_unter_Deck__steering_device_integrated_inside_canvas.JPG');
INSERT INTO MONUMENTO (ID, COD_PAIS, NOMBRE_PAIS, NOMBRE_CIUDAD, LATITUD, LONGITUD, NOMBRE_MONUMENTO, DESCRIPCION, FOTO_URL) VALUES (NEXTVAL('MONUMENTO_SEQ'),'UK','Reino Unido','Londres', 20.2, 22.4, 'Big Ben','El error habitual es llamar Big Ben a la torre, cuando en realidad es solo la enorme campana del reloj que marca puntualmente las horas. La torre de Westminster, sede del Parlamento Británico, se llamó Clock Tower hasta 2012','https://www.empacher.com/fileadmin/EN/products/racing-boats/racing-four/Steuer_unter_Deck__steering_device_integrated_inside_canvas.JPG');

ALTER SEQUENCE MONUMENTO_SEQ RESTART WITH 100 INCREMENT BY 1;
